# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='detail',
            field=models.TextField(default='', verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='files',
            name='desc',
            field=models.CharField(max_length=120, verbose_name='概要'),
        ),
    ]
