# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170716_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.CharField(default='', max_length=20, verbose_name='文件大小'),
        ),
    ]
