# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_files_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='size',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='文件大小'),
        ),
    ]
